ARG BASE_DOCKER=rocm/pytorch:latest
FROM $BASE_DOCKER
ENV WORKSPACE_DIR=/workspace
ENV STAGE_DIR=/workspace/installs
RUN mkdir -p $WORKSPACE_DIR
RUN mkdir -p ${STAGE_DIR}
WORKDIR $WORKSPACE_DIR


WORKDIR $WORKSPACE_DIR
COPY . Megatron-LM

# RUN cd Megatron-LM 
# #&&\
# #    pip install -e .

WORKDIR $WORKSPACE_DIR/Megatron-LM
# record configuration for posterity
RUN pip list

