ARG BASE_DOCKER=rocm/pytorch:latest
FROM $BASE_DOCKER

ARG PYTORCH_ROCM_ARCH_OVERRIDE="gfx942"
ENV WORKSPACE_DIR=/workspace
ENV STAGE_DIR=/workspace/installs
RUN mkdir -p $WORKSPACE_DIR
RUN mkdir -p ${STAGE_DIR}

RUN pip3 install \
numpy==1.26.4 \
scipy \
einops \
flask-restful \
nltk \
pytest \
pytest-cov \
pytest_mock \
pytest-csv \
pytest-random-order \
sentencepiece \
wrapt \
zarr \
wandb \
tensorstore==0.1.45 \
pytest_mock \
pybind11 \
setuptools==69.5.1 \
datasets \
tiktoken \
pynvml

WORKDIR $WORKSPACE_DIR
COPY . Megatron-LM
WORKDIR $WORKSPACE_DIR/Megatron-LM

# record configuration for posterity
RUN pip list

